### ISSUE TITLE
Not able to download on macOS

### ISSUE THREAD

**Issue by ankitsharma07** [yig/PySPQR#14]
I have tried downloading sparseqr using pip2 but always ended up with this error--

`ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-2.7
    creating build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/sparseqr_gen.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/cffi_asarray.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/sparseqr.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    running build_ext
    generating cffi module 'build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c'
    creating build/temp.macosx-10.14-x86_64-2.7
    building 'sparseqr._sparseqr' extension
    creating build/temp.macosx-10.14-x86_64-2.7/build
    creating build/temp.macosx-10.14-x86_64-2.7/build/temp.macosx-10.14-x86_64-2.7
    clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/suitesparse -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c -o build/temp.macosx-10.14-x86_64-2.7/build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.o
    build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c:492:10: fatal error: 'SuiteSparseQR_C.h' file not found
    #include <SuiteSparseQR_C.h>
             ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1`

When I tried pip3 it was downloaded successfully. I installed suite-sparse using Homebrew.

**Comment by yig** [comment]
That is strange. Are you using pip2 and pip3 on the same computer?

**Comment by ankitsharma07** [comment]
I tried using both. 

I have installed suite-sparse using `brew install suite-sparse` and it worked fine.

Then I tried `pip2 install sparseqr` and it generated the above error while by using `pip3 install sparseqr` everything worked.

I have to use sparseqr library for python 2 so, any help would be appreciated.

**Comment by yig** [comment]
It's very odd, since it's looking for a header file outside of the python installation, and installing via `pip3` had no problem. I just tested a python 2.7 virtual environment and had no trouble installing `sparseqr`:

```
yotronagon:pyspqr yotam$ python2 -m virtualenv new
...
yotronagon:pyspqr yotam$ cd new/
yotronagon:new yotam$ source bin/activate
(new)yotronagon:new yotam$ ./bin/pip install sparseqr
...
Successfully installed cffi-1.12.3 numpy-1.16.3 pycparser-2.19 scipy-1.2.1 sparseqr-1.0.0
(new)yotronagon:new yotam$ ./bin/python
Python 2.7.15 (default, Sep 18 2018, 20:30:39) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.43.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sparseqr
>>> 
```

**Comment by ankitsharma07** [comment]
I also tried with the virtual environment.

Still the same error

`(test) ➜  ~ pip install sparseqr
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting sparseqr
  Using cached https://files.pythonhosted.org/packages/24/03/ebddf9053067465f271cc879a6fe1d97bf3eef1d89f45fff051c81136418/sparseqr-1.0.0.tar.gz
Collecting numpy (from sparseqr)
  Downloading https://files.pythonhosted.org/packages/6e/36/e8369aa628b29f50211ba82daec31cc110f6627feca160bc11b0e4ee1191/numpy-1.16.3-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
     |████████████████████████████████| 13.9MB 16.3MB/s 
Collecting scipy (from sparseqr)
  Downloading https://files.pythonhosted.org/packages/85/70/9f8f1e9ed9fd33b96bb27fb080171fb571f7d33fecbd857e9f504e6dcc9a/scipy-1.2.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (27.4MB)
     |████████████████████████████████| 27.4MB 503kB/s 
Collecting cffi>=1.0.0 (from sparseqr)
  Using cached https://files.pythonhosted.org/packages/16/f6/46a3dece43541b2cbf3776ec2299e370a2408d9380958401cacb6d101853/cffi-1.12.3-cp27-cp27m-macosx_10_6_intel.whl
Collecting pycparser (from cffi>=1.0.0->sparseqr)
Building wheels for collected packages: sparseqr
  Building wheel for sparseqr (setup.py) ... error
  ERROR: Complete output from command /Users/ankitsharma/test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-install-4fLSlz/sparseqr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-wheel-RQKdcc --python-tag cp27:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-2.7
  creating build/lib.macosx-10.14-x86_64-2.7/sparseqr
  copying sparseqr/sparseqr_gen.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
  copying sparseqr/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
  copying sparseqr/cffi_asarray.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
  copying sparseqr/sparseqr.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
  running build_ext
  generating cffi module 'build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c'
  creating build/temp.macosx-10.14-x86_64-2.7
  building 'sparseqr._sparseqr' extension
  creating build/temp.macosx-10.14-x86_64-2.7/build
  creating build/temp.macosx-10.14-x86_64-2.7/build/temp.macosx-10.14-x86_64-2.7
  clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/suitesparse -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c -o build/temp.macosx-10.14-x86_64-2.7/build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.o
  build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c:492:10: fatal error: 'SuiteSparseQR_C.h' file not found
  #include <SuiteSparseQR_C.h>
           ^~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for sparseqr
  Running setup.py clean for sparseqr
Failed to build sparseqr
Installing collected packages: numpy, scipy, pycparser, cffi, sparseqr
  Running setup.py install for sparseqr ... error
    ERROR: Complete output from command /Users/ankitsharma/test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-install-4fLSlz/sparseqr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-record-ZVJUIm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ankitsharma/test/bin/../include/site/python2.7/sparseqr:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-2.7
    creating build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/sparseqr_gen.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/__init__.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/cffi_asarray.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    copying sparseqr/sparseqr.py -> build/lib.macosx-10.14-x86_64-2.7/sparseqr
    running build_ext
    generating cffi module 'build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c'
    creating build/temp.macosx-10.14-x86_64-2.7
    building 'sparseqr._sparseqr' extension
    creating build/temp.macosx-10.14-x86_64-2.7/build
    creating build/temp.macosx-10.14-x86_64-2.7/build/temp.macosx-10.14-x86_64-2.7
    clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/suitesparse -I/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c -o build/temp.macosx-10.14-x86_64-2.7/build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.o
    build/temp.macosx-10.14-x86_64-2.7/sparseqr._sparseqr.c:492:10: fatal error: 'SuiteSparseQR_C.h' file not found
    #include <SuiteSparseQR_C.h>
             ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command "/Users/ankitsharma/test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-install-4fLSlz/sparseqr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-record-ZVJUIm/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ankitsharma/test/bin/../include/site/python2.7/sparseqr" failed with error code 1 in /private/var/folders/v0/_vh8h6y1225czt7r94l4qys00000gn/T/pip-install-4fLSlz/sparseqr/
(test) ➜  ~ 
`

**Comment by yig** [comment]
I don't know how to debug this. It's very strange that it compiles with Python 3 on your same machine. Can you uninstall the Python 3 version and reinstall it to verify? Or reinstall your suite sparse with Homebrew?

**Comment by yig** [comment]
Python 2 is end of life, so I'm marking this as closed.
