### ISSUE TITLE
qr() got an unexpected keyword argument 'economy'

### ISSUE THREAD

**Issue by yustiks** [yig/PySPQR#16]
Hello,
I am trying to run the code and have the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-73-0ceea0ee1cbe> in <module>
     39 print("Q shape:", Q.shape)  # Q shape: (20, 20)
     40 print("R shape:", R.shape)  # R shape: (20, 5)
---> 41 Q, R, E, rank = sparseqr.qr( M, economy=True )
     42 print("Q shape:", Q.shape)  # Q shape: (20, 5)
     43 print("R shape:", R.shape)  # R shape: (5, 5)

TypeError: qr() got an unexpected keyword argument 'economy'
```

**Comment by yustiks** [comment]
what could be the reason?

**Comment by BurningKarl** [comment]
I'm not the developer but I would suspect an outdated version of the sparseqr package. The version released on PyPI was published in 2017 and does not include the `economy` option. Try uninstalling your current version and install the version published on GitHub:

```
pip install git+https://github.com/yig/PySPQR.git#egg=sparseqr
```

**Comment by yig** [comment]
The version on PyPI has been updated. Marking as closed.
