### ISSUE TITLE
usage example not working

### ISSUE THREAD

**Issue by johann50** [yig/PySPQR#4]
FIrst of all, thanks for your work. This code will be very useful to people
doing sparse least squares.  I installed the code fine but got the following fixes and
problems for the 'Usage' code that is on the github webpage.  I am 
running python3.4,  scipy 0.19, numpy-1.13,  cffi-1.10, linux-3.19 

PROBLEM 1.
Got the error message:
result = scipy.sparse.linalg.spsolve(R, Qb)
AttributeError: 'module' object has no attribute 'linalg'

This was fixed by adding the import:
import scipy.sparse.linalg
 
PROBLEM 2
"CHOLMOD error: A and B must have the same # of rows"
from the following line:
x = spqr.qr_solve( A, b, tolerance = 0 )
I fixed this problem by changing the dimension of b from 10 to 20.
Had to reset this to the original dimension of 10 afterwards in order to avoid another
error message in the subsequent code.   

PROBLEM 3
But now I get the error message:
"MatrixRankWarning: Matrix is exactly singular" from the line:
scipy.sparse.linalg.spsolve(R, Qb)

**Comment by yig** [comment]
Thank you for pointing this out. I fixed the usage examples.

**Comment by johann50** [comment]
PROBLEM 3 is not resolved.

**Comment by johann50** [comment]
Sorry.  Its OK now.  Thanks.
